### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by santosharjun** [twain47/Nominatim#371]
Using an 8-core 56GB server on Azure.

Import
osm2pgsql SVN version 0.87.3-dev (64bit id space)

Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping
Allocating memory for sparse node cache
Node-cache: cache=512MB, maxblocks=65536*8192, allocation method=9
Mid: pgsql, scale=10000000 cache=512
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /usr/local/india-latest.osm.pbf

Processing: Node(43870k 70.8k/s) Way(0k 0.00k/s) Relation(0 0.00/s)^MProcessing: Node(43880k 70.8k/s) Way(0k 0.00k/s) Relation(0 0.00/s)^MProcessing: Node(43890k 70.8k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Segmentation fault (core dumped)

ERROR: Error executing external command: /usr/local/Nominatim-2.4.0/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore -C 512 -P 5432 -d nominatim /usr/local/india-latest.osm.pbf --cache-strategy sparse
Error executing external command: /usr/local/Nominatim-2.4.0/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore -C 512 -P 5432 -d nominatim /usr/local/india-latest.osm.pbf --cache-strategy sparse

**Comment by mtmail** [comment]
The Azure virtual machine might be set up without swap space. Have a look at https://github.com/twain47/Nominatim/issues/306 on how to configure that. As you see I ran into the same issue with a DigitalOcean virtual machine.

Less likely it might be that osm2pgsql got compiled as 32bit binary instead of 64bit. https://github.com/openstreetmap/osm2pgsql/issues/23

I notice you placed Nominatim into `/usr/local/`. Does that mean you run all commands as the root user? That would cause trouble later when you setup the website to display results.

**Comment by santosharjun** [comment]
tried creating a swap file as mentioned in #306 but still same error is coming :(

dd if=/dev/zero of=/root/myswapfile bs=1M count=8000
chmod 600 /root/myswapfile
mkswap /root/myswapfile
swapon /root/myswapfile

**Comment by lonvia** [comment]
8GB is not enough, you'd need 30 or 40G. Have you switched off overcommit on your machine (a bad advice given in certain blog post)? Then switch it back on (vm.overcommit_memory=0). There is also a `--cache-strategy sparse` in your command line. If you have added such a parameter, remove it again. It's not a good idea for something as large as India. You should increase `--osm2pgsql-cache` to at least 5000 to speed up the import.

Finally, I would recommend to use the latest git version of Nominatim which is the soon-to-be-released 2.5. I vaguely remember that a segfault bug was fixed in osm2pgsql in the meantime although I'm not sure it is exactly what you see.

**Comment by santosharjun** [comment]
Disabled sparse strategy and increased Swap cache size to 21GB ( 21GB*4=84GB for a 16 core system) but still fails at the same place with same error.

tried the small Luxemburg, but still same error. Looks like I need that osm2pgsql bug fix to get through this.


Reading in file: /usr/local/luxembourg-latest.osm.pbf
Processing: Node(1570k 78.5k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Segmentation fault (core dumped)
ERROR: Error executing external command: /usr/local/Nominatim-2.4.0/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore -C 2048 -P 5432 -d nominatim /usr/local/luxembourg-latest.osm.pbf
Error executing external command: /usr/local/Nominatim-2.4.0/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore -C 2048 -P 5432 -d nominatim /usr/local/luxembourg-latest.osm.pbf

**Comment by santosharjun** [comment]
Pulled latest from GIT and tried the smallest Luxembourg and still the same issue 

osm2pgsql SVN version 0.89.0-dev (64bit id space)

Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=128MB, maxblocks=16384*8192, allocation method=11
Mid: pgsql, scale=10000000 cache=128
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /usr/local/luxembourg-latest.osm.pbf
Using PBF parser.
Processing: Node(1570k 65.4k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Segmentation fault (core dumped)
ERROR: Error executing external command: /home/egnom/nominatim/Nominatim/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 128 -P 5432 -d nominatim /usr/local/luxembourg-latest.osm.pbf
Error executing external command: /home/egnom/nominatim/Nominatim/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 128 -P 5432 -d nominatim /usr/local/luxembourg-latest.osm.pbf

**Comment by santosharjun** [comment]
Should I use different postGIS or pgsql version?

**Comment by lonvia** [comment]
This sounds more like an osm2pgsql issue then. Could you please download and compile [the latest git version of osm2pgsql](https://github.com/openstreetmap/osm2pgsql) and try to run a standard import with your luxembourg extract (osm2pgsql -sc -S default.style). If this still results in a segfault, then you should open a ticket with osm2pgsql.

**Comment by santosharjun** [comment]
Issue is not reproducible with a clean installation. closing. Thanks for all the help.
